Web/Models/PluckList.cs
namespace Web.Models;

public class PluckList
{
    public Guid Id;
    public string Name;
    public string Shipment;
    public string Address;
    public List<PluckListItem> Items;
    public bool Archived;
}

Web/Controllers/PluckListController.cs
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Web.Controllers;

public class PluckListController : Controller
{
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var httpClient = new HttpClient();
        var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "http://localhost:5000/plucklists"));
        var json = await response.Content.ReadAsStringAsync();
        var pluckLists = JsonConvert.DeserializeObject<List<BasePluckList>>(json);
        ViewData["PluckLists"] = pluckLists;
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreatePluckList()
    {
        List<string> missing = [];
        if (!Request.Form.TryGetValue("name", out var name) || name[0]!.Length == 0) missing.Add("name");
        if (!Request.Form.TryGetValue("shipment", out var shipment) || shipment[0]!.Length == 0) missing.Add("shipment");
        if (!Request.Form.TryGetValue("address", out var address) || address[0]!.Length == 0) missing.Add("address");
        if (!Request.Form.TryGetValue("items", out var items) || items[0]!.Length == 0) missing.Add("items");
        if (missing.Count != 0) return RedirectToAction(nameof(Create));
        var httpClient = new HttpClient();
        var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/plucklists/create");
        var formData = new Dictionary<string, string>
        {
            { "name", name! },
            { "shipment", shipment! },
            { "address", address! },
            { "items", items! },
        };
        request.Content = new FormUrlEncodedContent(formData);
        var response = await httpClient.SendAsync(request);
        return RedirectToAction(response.IsSuccessStatusCode ? nameof(Index) : nameof(Create));
    }
}

Web/Controllers/PluckListsController.cs
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web.Models;

namespace Web.Controllers;

public class PluckListsController : Controller
{
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var httpClient = new HttpClient();
        var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "http://localhost:5000/plucklists"));
        var json = await response.Content.ReadAsStringAsync();
        var pluckLists = JsonConvert.DeserializeObject<List<FullPluckList>>(json)?.Select(pluckList => new PluckList
        {
            Id = pluckList.Id,
            Name = pluckList.Name,
            Shipment = pluckList.Shipment,
            Address = pluckList.Address,
            Archived = pluckList.Archived
        }).ToList() ?? [];
        pluckLists.Sort((o1, o2) => o1.Archived.CompareTo(o2.Archived));
        ViewData["PluckLists"] = pluckLists;
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreatePluckList()
    {
        List<string> missing = [];
        if (!Request.Form.TryGetValue("name", out var name) || name[0]!.Length == 0) missing.Add("name");
        if (!Request.Form.TryGetValue("shipment", out var shipment) || shipment[0]!.Length == 0) missing.Add("shipment");
        if (!Request.Form.TryGetValue("address", out var address) || address[0]!.Length == 0) missing.Add("address");
        if (!Request.Form.TryGetValue("items", out var items) || items[0]!.Length == 0) missing.Add("items");
        if (missing.Count != 0) return RedirectToAction(nameof(Create));
        var httpClient = new HttpClient();
        var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5000/plucklists/create");
        var formData = new Dictionary<string, string>
        {
            { "name", name! },
            { "shipment", shipment! },
            { "address", address! },
            { "items", items! },
        };
        request.Content = new FormUrlEncodedContent(formData);
        var response = await httpClient.SendAsync(request);
        return RedirectToAction(response.IsSuccessStatusCode ? nameof(Index) : nameof(Create));
    }
}

Web/Views/PluckList/Create.cshtml
<h1>Create PluckList</h1>
<form asp-controller="PluckList" asp-action="CreatePluckList" method="post">
    <label>Name:
        <input type="text" name="name"/>
    </label><br/>
    <label>Shipment:
        <input type="text" name="shipment"/>
    </label><br/>
    <label>Address:
        <input type="text" name="address"/>
    </label><br/>
    <label>Items:
        <input type="text" name="items"/>
    </label><br/>
    <button type="submit">Submit</button>
</form>

Web/Views/PluckList/Index.cshtml
@using Core.Models
<div>
    <h1>PluckLists</h1>
    <a asp-action="Create">Create</a>
    <hr/>
    
    <table class="table table-striped" style="width:100%; border: 1px solid #888;">
        <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Shipment</th>
            <th>Address</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var pluckList in (List<BasePluckList>)ViewData["PluckLists"]!)
        {
            <tr>
                <td>@pluckList.Name</td>
                <td>@pluckList.Shipment</td>
                <td>@pluckList.Address</td>
            </tr>
        }
        </tbody>
    </table>
</div>